#!/usr/bin/env bash
# Build the JuristAI logo sting and mux it onto the rendered animation.
#
# The audio is SYNTHESIZED, not licensed: every element is generated by ffmpeg
# from sine and noise sources, so there is no third-party track to clear before
# using this in a submission, an ad, or an app store listing.
#
# Every cue lands on an animation beat (see public/logo-animation.html):
#   0.05 / 0.20 / 0.35s  three soft air swells   — the rings drawing in
#   0.90s                warm chime              — the "J" appears
#   1.25s                quiet high ping         — the diamond
#   1.50s                A-major chord swell     — the wordmark
#   2.75s                fade out                — with the visual fade
#
# Design intent: restrained and warm. A legal brand should sound certain, not
# excited — so no bright synth stabs, no riser, nothing percussive.
#
# Usage:  scripts/render-logo-audio.sh <ffmpeg> <video-in.mp4> <video-out.mp4> [audio-out.wav]

set -euo pipefail

FF="${1:?path to ffmpeg required}"
VIDEO_IN="${2:?input video required}"
VIDEO_OUT="${3:?output video required}"
AUDIO_OUT="${4:-/tmp/juristai-sting.wav}"

# Must match the rendered animation. The fade-out variant runs 3.23s and ducks
# with the visual fade; the hold-on-logo variant (FADE=0 render) runs 2.80s and
# should RESOLVE instead — a sting that ducks while the logo is still on screen
# sounds like a mistake.
#   fade-out clip:  DUR=3.23 FADE_ST=2.75 FADE_D=0.46   (defaults)
#   hold clip:      DUR=2.80 FADE_ST=2.50 FADE_D=0.30
DUR="${DUR:-3.23}"
FADE_ST="${FADE_ST:-2.75}"
FADE_D="${FADE_D:-0.46}"
MASTER_GAIN="${MASTER_GAIN:-10.5dB}"  # peak lands near -3 dBFS; the limiter is
                                      # the safety net, not the level control

# ── Synthesize ──────────────────────────────────────────────────────────────
# Levels are set per element and amix runs with normalize=0, so the balance is
# explicit rather than whatever averaging happens to produce. A limiter catches
# the sum.
#
# SOURCE NORMALIZATION: ffmpeg's `sine` generator peaks around -18 dBFS while
# `anoisesrc` peaks near 0 dBFS. Mixing them with naive volume numbers makes
# every tonal element 18 dB too quiet — the first render had the background
# ring swells sitting at the same level as the hero chime. Each sine is lifted
# by 18 dB FIRST, so the volume figures below read as a real balance.
"$FF" -y -hide_banner -loglevel error \
  -f lavfi -i "sine=f=440:d=2.4"        `# chime fundamental  (A4)` \
  -f lavfi -i "sine=f=880:d=2.4"        `# chime 2nd partial` \
  -f lavfi -i "sine=f=1320:d=2.4"       `# chime 3rd partial` \
  -f lavfi -i "sine=f=1318.51:d=1.0"    `# diamond ping       (E6)` \
  -f lavfi -i "sine=f=110:d=2.0"        `# chord root         (A2)` \
  -f lavfi -i "sine=f=220:d=2.0"        `#                    (A3)` \
  -f lavfi -i "sine=f=277.18:d=2.0"     `# major third        (C#4)` \
  -f lavfi -i "sine=f=329.63:d=2.0"     `# fifth              (E4)` \
  -f lavfi -i "anoisesrc=c=pink:d=0.7:r=48000" \
  -f lavfi -i "anoisesrc=c=pink:d=0.7:r=48000" \
  -f lavfi -i "anoisesrc=c=pink:d=0.7:r=48000" \
  -f lavfi -i "anoisesrc=c=brown:d=${DUR}:r=48000" \
  -filter_complex "
    [0]volume=18dB,volume=0.50,afade=t=out:st=0:d=1.9:curve=exp[b0];
    [1]volume=18dB,volume=0.20,afade=t=out:st=0:d=1.2:curve=exp[b1];
    [2]volume=18dB,volume=0.09,afade=t=out:st=0:d=0.7:curve=exp[b2];
    [b0][b1][b2]amix=inputs=3:normalize=0,adelay=900:all=1[chime];

    [3]volume=18dB,volume=0.15,afade=t=out:st=0:d=0.9:curve=exp,adelay=1250:all=1[ping];

    [4]volume=18dB,volume=0.34[c0];
    [5]volume=18dB,volume=0.20[c1];
    [6]volume=18dB,volume=0.12[c2];
    [7]volume=18dB,volume=0.12[c3];
    [c0][c1][c2][c3]amix=inputs=4:normalize=0,
      afade=t=in:st=0:d=0.5,afade=t=out:st=1.15:d=0.85,
      adelay=1500:all=1[chord];

    [8]lowpass=f=1100,volume=0.085,afade=t=in:st=0:d=0.14,afade=t=out:st=0.16:d=0.45,adelay=50:all=1[r1];
    [9]lowpass=f=1100,volume=0.075,afade=t=in:st=0:d=0.14,afade=t=out:st=0.16:d=0.45,adelay=200:all=1[r2];
    [10]lowpass=f=1100,volume=0.065,afade=t=in:st=0:d=0.14,afade=t=out:st=0.16:d=0.45,adelay=350:all=1[r3];

    [11]lowpass=f=420,volume=0.030,afade=t=in:st=0:d=0.9,afade=t=out:st=2.30:d=0.9[air];

    [chime][ping][chord][r1][r2][r3][air]amix=inputs=7:normalize=0,
      aecho=0.85:0.5:65:0.16,
      volume=${MASTER_GAIN},
      alimiter=limit=0.95,
      afade=t=out:st=${FADE_ST}:d=${FADE_D},
      atrim=0:${DUR},asetpts=PTS-STARTPTS,
      aformat=sample_fmts=s16:sample_rates=48000:channel_layouts=stereo
  " "$AUDIO_OUT"

# ── Mux (video stream copied — no re-encode, no generation loss) ────────────
"$FF" -y -hide_banner -loglevel error \
  -i "$VIDEO_IN" -i "$AUDIO_OUT" \
  -c:v copy -c:a aac -b:a 192k -ar 48000 -ac 2 \
  -shortest -movflags +faststart "$VIDEO_OUT"

echo "audio  -> $AUDIO_OUT"
echo "video  -> $VIDEO_OUT"
